celery_start_result:
  failed: yes
