---

- block:
    - fail:
        msg: 'Deploy code from a local directory to receive the generated migration files'
      when: not djsite_repository_is_local|bool

    - name: Make database migrations
      command: >
        {{ djsite_app_directory }}/test/venv/bin/python manage.py makemigrations {{ djsite_config.custom_applications|join(' ') }}
      args:
        chdir: '{{ djsite_app_directory }}/test/server'
      changed_when: _djsite_make_migrations.stdout_lines|length > 1
      register: _djsite_make_migrations

    - name: Generate graphs of the models
      shell: >
        {{ djsite_app_directory }}/test/venv/bin/python
        ../manage.py graph_models | dot -Tpng -omigrations/models.png
      args:
        chdir: '{{ djsite_app_directory }}/test/server/{{ item }}'
      loop: '{{ djsite_config.custom_applications }}'
      when: djsite_graph_models_enabled|bool

    - name: Copy the database migrations in the local machine
      synchronize:
        src: '{{ djsite_app_directory }}/test/server/{{ item }}/migrations/'
        dest: '{{ djsite_repository_url }}/{{ djsite_config.source_path }}/{{ item }}/migrations/'
        archive: yes
        checksum: yes
        delete: yes
        mode: pull
        rsync_opts:
          - --omit-dir-times
          - --exclude
          - __pycache__/
          - --exclude
          - '*.pyc'
      loop: '{{ djsite_config.custom_applications }}'
  become: yes
  become_user: '{{ djsite_daemon_user }}'
  tags: [django-site, database, update] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
